from config import sql
import db

sql.create_all()

user = db.User(name='Sang', email='u1@gmail.com')
user.set_password('1234')
user2 = db.User(name='User 2', email='u2@gmail.com')
user2.set_password('1234')
genre = db.Genre(name='Genre 1')
album = db.Album(title='Album 1', cover_image='al-1', genres_id=1, added_by_user_id=1)
album2 = db.Album(title='Album 2', cover_image='al-2', genres_id=1, added_by_user_id=1)
album3 = db.Album(title='Album 3', cover_image='al-3', genres_id=1, added_by_user_id=1)
track = db.Track(name='Track 1', duration=120, album_id=1, added_by_user_id=1)
track2 = db.Track(name='Track 2', duration=120, album_id=1, added_by_user_id=1)
playlist = db.Playlist(name='Playlist 1', image='pl1.jpg', is_public=True, added_by_user_id=1)
playlist2 = db.Playlist(name='Playlist 2', image='pl2.jpg', is_public=True, added_by_user_id=1)
played = db.Played(user_id=1, track_id=1, count=1)
played2 = db.Played(user_id=1, track_id=2, count=1)
played3 = db.Played(user_id=1, track_id=1, count=2)

sql.session.add(user)
sql.session.add(user2)
sql.session.add(album)
sql.session.add(album2)
sql.session.add(album3)
sql.session.add(track)
sql.session.add(track2)
sql.session.add(playlist)
sql.session.add(playlist2)
sql.session.add(genre)
sql.session.add(played)
sql.session.add(played2)
sql.session.add(played3)
sql.session.commit()
