from config import sql
import db

sql.create_all()

user = db.User(name='Sang', email='u1@gmail.com')
user.set_password('1234')
user2 = db.User(name='User 2', email='u2@gmail.com')
user2.set_password('1234')
artist = db.Artist(name='Artist 1', avatar_file='at-1', cover_file='at-cv-1', description='hông có gì cả!!')
artist2 = db.Artist(name='Artist 2', avatar_file='at-2', cover_file='at-cv-2', description='hông có gì cả!!')
artist3 = db.Artist(name='Artist 3', avatar_file='at-3', cover_file='at-cv-3', description='hông có gì cả!!')
user.created_artists.append(artist)
user.created_artists.append(artist2)
user.created_artists.append(artist3)
genre = db.Genre(name='Genre 1')
genre2 = db.Genre(name='Genre 2')
album = db.Album(title='Album 1', cover_image='al-1', year_release=2021)
album2 = db.Album(title='Album 2', cover_image='al-2', year_release=2020)
album3 = db.Album(title='Album 3', cover_image='al-3', year_release=2018)
genre.albums.append(album)
genre.albums.append(album2)
genre2.albums.append(album3)
user.created_albumes.append(album)
user.created_albumes.append(album2)
user.created_albumes.append(album3)
track = db.Track(name='Track 1', duration=120)
track2 = db.Track(name='Track 2', duration=120)
genre.tracks.append(track)
genre.tracks.append(track2)
user.created_tracks.append(track)
user.created_tracks.append(track2)
track.artists.append(artist)
track.artists.append(artist2)
track2.artists.append(artist)
album.artists.append(artist)
album.artists.append(artist2)
album2.artists.append(artist2)
album3.artists.append(artist3)
album.tracks.append(track)
album.tracks.append(track2)
playlist = db.Playlist(name='Playlist 1', image='pl1.jpg', is_public=True)
playlist2 = db.Playlist(name='Playlist 2', image='pl2.jpg', is_public=True)
user.created_playlists.append(playlist)
user.created_playlists.append(playlist2)
playlist.tracks.append(track)
playlist.tracks.append(track2)
played = db.Played(user_id=1, track_id=1, count=1)
played2 = db.Played(user_id=1, track_id=2, count=1)
played3 = db.Played(user_id=1, track_id=1, count=2)

sql.session.add(user)
sql.session.add(user2)
sql.session.add(genre)
sql.session.add(genre2)
sql.session.add(played)
sql.session.add(played2)
sql.session.add(played3)
sql.session.commit()
